fal-ai/isolate

- Dockerfile
Adds a Dockerfile for making it easy to build a server container
> Dockerize isolate server

- src/isolate/backends/connections/__init__.py
- src/isolate/backends/connections/agent_startup.py
- src/isolate/backends/connections/ipc/__init__.py
- src/isolate/backends/connections/ipc/_base.py
- src/isolate/backends/connections/ipc/agent.py
- src/isolate/server/_runs.py
- tests/test_ipc.py
* #30
* #29
* #28
* #27
* #25
* #23
* #22
* #21
* #20
* __->__ #19
> feat: unify extended Python IPC & consolidate agent startup logic

- src/isolate/backends/connections/common.py
- tests/test_serialization.py
* #30
* #29
* #28
* #27
* #25
* #23
* #22
* #21
* __->__ #20
* #19
> feat: consolidate serialization/deserialization for proper error handling

- tools/regen_grpc.py
* #30
* #29
* #28
* #27
* #25
* #23
* #22
* __->__ #21
* #20
* #19
> misc: add gRPC definition generator

- src/isolate/backends/common.py
- src/isolate/backends/conda.py
- src/isolate/backends/context.py
- src/isolate/backends/virtual_env.py
- tests/test_common.py
* #30
* #29
* #28
* #27
* __->__ #25
* #23
* #22
> fix: use a different staging place when building environments

- tools/Dockerfile
- tools/requirements.txt
> cleanup [4/4]: Docker image

- .github/workflows/test.yml
- pyproject.toml
- src/isolate/backends/pyenv.py
- tests/test_backends.py
> feat: Implement a Pyenv backend (FEA-566)

- src/isolate/backends/virtualenv.py
- tests/test_backends.py
> feat: improve handling of missing Python versions in virtualenv (FEA-585)

- src/isolate/backends/virtualenv.py
- tests/test_backends.py
> feat: install missing Python versions for virtualenv with pyenv (FEA-586)

- src/isolate/registry.py
> fix: handle setuptools-based installations in the registry as well (FEA-661)

- src/isolate/server/server.py
- tests/test_server.py
> fix: properly coalesce build logs from agent environment (FEA-662)

- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
- src/isolate/backends/conda.py
- tests/test_backends.py
- tools/Dockerfile
- tools/agent_requirements.txt
Here's what an example script with conda env yml could look like:
```
from isolate.backends.remote import IsolateServer
with open("env.yaml") as f:
env_yml_str = f.read()
target_config = {
"kind": "conda",
"configuration": {
"env_yml_str": env_yml_str
}
}
config = {
"host": "localhost:50001",
"target_environments": [target_config]
}
env = IsolateServer.from_config(config)
```
Where `env.yaml` is:
```
name: testo
channels:
- defaults
dependencies:
- python=3.8.10
- pip=20.3
- pip:
- isolate==0.7.1
- dill==0.3.6
```
> feat: handle conda env ymls

- src/isolate/backends/common.py
- tests/test_server.py
This PR changes the IO observers from "break up every 0.1 seconds and collect all logs (if there are any) until the process is dead" to "poll the stdout/stderr until you receive something OR 0.1 seconds passes, handle everything you received, check if the process is dead and if it is then exit". This allows it to instantly get all the new logs and forward them to the user (through `hook()` which is adding to the queue).
> fix: instant io observers with select()

- src/isolate/server/server.py
- tests/test_server.py
If the underlying process crashes during the first run, the worker still thinks it can re-use its channel for the next request with the assumption that our 'agent's are highly unlikely to crash. Although it is not very true, since even the most simple OOM or loading a c library (e.g. it segfaults / something is broken) will completely kill our agent process and all the upcoming connections will try to use the same machine.
The current solution here uses the native gRPC callbacks to watch the status of the channel (not the service). If the underlying channel goes bad (basically an HTTP connection to the gRPC server running inside the agent) for any reason, we can determine that agent is not useful / bad and spawn a new one. From what I understand, this behavior relies on keepalives …
> fix: handle failures of kept alive processes

- LICENSE
fixes: #108
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
> Add License to the Project

- tools/agent_requirements.txt
- tools/requirements.txt
- tools/test_agent_requirements.txt
> build: add cloudpickle to agent requirements

- src/isolate/server/definitions/server.proto
- src/isolate/server/definitions/server_pb2.py
- src/isolate/server/definitions/server_pb2.pyi
- src/isolate/server/definitions/server_pb2_grpc.py
- src/isolate/server/server.py
- tests/test_server.py
Very basic version to start trying it out e2e.
> feat: introduce basic Submit

- src/isolate/connections/_local/_base.py
- src/isolate/connections/grpc/agent.py
This is useful for debugging at the very least.
> feat: set ISOLATE_SERVER_VERSION for agent

- src/isolate/server/definitions/server.proto
- src/isolate/server/definitions/server_pb2.py
- src/isolate/server/definitions/server_pb2.pyi
- src/isolate/server/definitions/server_pb2_grpc.py
- src/isolate/server/server.py
- tests/test_server.py
This is not needed for our own use right now, but very handy to have for a piece of mind/testing/debugging.
> feat: introduce List and Cancel

- src/isolate/server/server.py
> fix: default to env logger

- src/isolate/server/server.py
Otherwise we might be trying to pickle it if any of our code imports this file. We have a class to put it into anyway for better resource management.
> chore: drop global RUNNER_THREAD_POOL

- src/isolate/backends/container.py
This is used in the controller, but same as requirements should be accepted by the env class.
> chore(container): accept resolver
