fal-ai/isolate

poetry.lock
pyproject.toml
src/isolate/server/_auth.py
src/isolate/server/_server.py
tests/test_server.py

Adds token based authentication to the Flask server
Features:
- Authentication off by default
- If `FAL_USER_NAME` is set, authentication is required
- Server prints out a token when it's started
- All requests must then include `x-access-token` header that contains a valid token
Example:
```
docker run -p 5000:5000 --env FAL_USER_NAME=testotesto falai/isolate
```
Prints out following:
```
++++
The following line contains your authentication token. Put it in 'x-access-token' header.
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ0ZXN0b3Rlc3RvIn0.RSORaI4bxkjNNU-LHaXEL1OSK5K1bXJx448aG4_ocBo
++++
* Serving Flask app 'isolate.server'
* Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
* Running on all …
```

Token based authentication for the server

---

pyproject.toml
src/isolate/backends/remote.py
src/isolate/registry.py
src/isolate/server/__init__.py
src/isolate/server/interface.py
tests/test_backends.py

While implementing support for isolate and isolate-server to dbt-fal, I noticed that we would need two different code paths in each implementation. This PR proposes a new environment backend that is (from a protocol level) is indistinguishable from local environments but actually runs your code in the isolate server. So with a single change (see `test_isolate_server_demo` for an example) in the definition, you can convert the existing environment into an environment on the cloud and start running your code as if it was in a local environment (same methods).

feat: Implement a client for isolate server as a new env

---

src/isolate/backends/conda.py
src/isolate/backends/local.py
src/isolate/backends/remote.py
src/isolate/backends/virtualenv.py
src/isolate/server/server.py
tests/test_backends.py
tests/test_server.py

No more confusion when `virtualenv with packages=[]` didn't install anything 🎉

fix: validate invalid parameters when initializing environments

---

src/isolate/backends/common.py
src/isolate/backends/settings.py
tests/test_common.py

Even though we had a good solution for dealing with this in the past, I've observed that it is not enough when we start a lot of different processes. The main problem is that we had to do two renames and in the midst from one to the other there might be other processes moving the environment. This PR moves this system to a more granular, lock based approach which should guarantee that a particular cache directory will only be modified by a single process at a time.

fix: high parallelism safe atomic cache locking

---

src/isolate/backends/common.py
src/isolate/backends/conda.py
src/isolate/backends/settings.py
tests/test_backends.py
tests/test_common.py

Seems like when building the environments from `/tmp/<build-dir>` to `/cache/<cache-id>`, some of the binaries still contain references to the `/tmp/<build-dir>` because of how conda links compiled binaries and their headers. We should be able to use `conda clone` as a proper way of moving the environments which figures out which parts reference a certain base path and then relinks them.

fix: Ensure conda environments are moved properly

---

src/isolate/connections/_local/_base.py
src/isolate/server/server.py
tests/test_backends.py

feat: Expose installed binaries under `PATH` for custom packages

---

src/isolate/connections/grpc/interface.py
src/isolate/logs.py
tests/test_loglevel.py

**Notes:**
This small change on the `LogLevel` enum was done to allow comparison between log levels so we can do log filtering when needed.
**Implementation details:**
- Remove the inheritance from `str` to allow custom comparison using `functools.total_ordering`.
- As far as I could assess, this is not a breaking change. The `__str__` is compatible with the previous assumption that the type was also a string. **However, errors might pop up** in case some consuming code assumed the type itself to also be a `str`.
If you have concerns with this approach, please leave a comment!
---
see https://github.com/fal-ai/fal-isolate-cloud/pull/272 for a related change that depends on log level comparison

feat: add log level comparison

---

src/isolate/server/server.py

haven't tested but looks like a super simple way to at least get the logs flowing in. cc: @chamini2

fix: send empty packet to the client every 600 seconds

---

pyproject.toml

Was lurking around and noticed that https://pypi.org/project/isolate/ doesn't have any links to the source repo.

pyproject: add a link to the github repo

---

src/isolate/backends/conda.py

A few days ago conda 24.3.0 removed `--force` completely causing this to no longer work. `--yes` has been around for more than a year now and we don't really need to support old conda/miniconda so we can just directly replace it and not bother with compatibility with older versions.
https://github.com/conda/conda/releases/tag/24.3.0
Discovered in https://github.com/fal-ai/isolate-cloud/pull/1676 and blocking it.

fix(conda): use --yes instead of --force

---

src/isolate/connections/common.py

Allows us to stop parsing messages.

chore(isolate): separate serialization and deserialization exceptions

---

src/isolate/connections/grpc/agent.py

We get DeserializationError there now, but really any exception can come up here (see the note), so we can catch BaseException and send it back to the user.

fix(agent): catch BaseException when deserializing user function

---

src/isolate/connections/common.py

These are unecessary and complicate pickling.

fix(isolate): don't use dataclass for serialization errors

---

src/isolate/backends/common.py
src/isolate/backends/conda.py
src/isolate/backends/pyenv.py
src/isolate/backends/virtualenv.py
src/isolate/connections/_local/_base.py
src/isolate/connections/grpc/_base.py
src/isolate/connections/grpc/agent.py
src/isolate/connections/ipc/_base.py
src/isolate/connections/ipc/agent.py

Had to also introduce `--log-fd` mechanism for agents, so we don't have a spaghetti of `Log` message logic in both server and agent (e.g. we were capturing USER logs through logged_io in server, but BRIDGE ones were in agent), which was not allowing this PR to be just  a oneliner `print(log)`.
Note that `--log-fd` mechanism doesn't change anything for the user, same messages are getting sent out, but now from only from server instead of from both server (this is where we were sending out USER logs) and agent (this is where we were sending BRIDGE logs).

chore: print agent logs in addition to sending over grpc

---

src/isolate/connections/grpc/agent.py

We need to keep backward compatibility with older clients and they will have trouble unpickling a new exception, as we are sending these out pickled by reference and not by value (solving that would require serialization backend specific actions, which I would rather avoid for now to unblock a release).

fix(agent): log exception instead of returning (revert #121)

---

src/isolate/backends/common.py
src/isolate/backends/conda.py
src/isolate/backends/pyenv.py
src/isolate/backends/virtualenv.py
src/isolate/connections/_local/_base.py
src/isolate/connections/grpc/_base.py
src/isolate/connections/grpc/agent.py
src/isolate/connections/ipc/_base.py
src/isolate/connections/ipc/agent.py

Additional note about why this will work with old applications (since this is not super trivial): we build multiple environments in server itself with the first one being an agent environment that uses requirements that we pass to it in `AGENT_REQUIREMENTS_TXT`, and this one is built no matter what application you are running and what requirements it might have. Then when spawning an agent and running user code in it, the environment they are running in has a chain of `PYTHONPATH`s that are inherited in an order that makes the first one (so the one from agent requirements txt) override anything after that, which means that no matter what user apps we are running our agent requirements will be the ones uses (including isolate), which makes this PR possible without breaking backward …

chore(grpc): print agent logs in addition to sending over grpc, v2

---

src/isolate/backends/container.py

It is a small convenience feature to identify environments better when requirements are populated.

feat(container): Add requirements property in case specified

---

src/isolate/connections/grpc/agent.py

These should be shown as regular runtime errors, similar to how it would appear locally or even similar to how a serialization error would look like on the client before they send the call out.
Note that these will be logged, but just not by the agent itself but by the server, same as user's stdout/stderr.

fix(agent): print serialization exceptions instead of logging

---

src/isolate/server/server.py

Probably not the best idea to reuse it, as grpc might do anything that it wishes to it. This is a suspected cause of a `RuntimeError('cannot schedule new futures after shutdown')` that I got during testing submit.

fix(server): don't reuse ThreadPoolExecutor between grpc and runners

---

src/isolate/logger.py

More accurate logs for requests

feat: add log timestamp when processing

---

.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml
src/isolate/backends/settings.py
src/isolate/connections/_local/_base.py
src/isolate/connections/grpc/_base.py
src/isolate/connections/ipc/_base.py
tests/test_backends.py
tests/test_server.py

These will be helpful to be able to filter which locks should be returned to the user and which ones should be hidden.

feat: introduce inferring of log levels

---

src/isolate/backends/common.py

Working with arabic in the output I'm sometimes seeing stuff like
```
Exception in thread Thread-3 (_reader):
Traceback (most recent call last):
File "/root/.pyenv/versions/3.12.4/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
self.run()
File "/root/.pyenv/versions/3.12.4/lib/python3.12/threading.py", line 1010, in run
self._target(*self._args, **self._kwargs)
File "/opt/venv/lib/python3.12/site-packages/isolate/backends/common.py", line 153, in _reader
forward_lines(fd)
File "/opt/venv/lib/python3.12/site-packages/isolate/backends/common.py", line 115, in forward_lines
raw_data = stream.read()
^^^^^^^^^^^^^
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4095: unexpected end of data
```
which breaks the rest …

fix: handle broken unicode

---

pyproject.toml

pytest doesn't have a native `flaky`, need to install it explicitly. Leftover from https://github.com/fal-ai/isolate/pull/163
```
/Users/runner/work/isolate/isolate/tests/test_server.py:558: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
```

fix: don't forget to install flaky

---

src/isolate/connections/_local/agent_startup.py

`.pth` could be model weights or python path configuration files https://docs.python.org/3/library/site.html Running into the former will result in:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/isolate/connections/_local/agent_startup.py", line 45, in <module>
load_pth_files()
File "/usr/local/lib/python3.11/site-packages/isolate/connections/_local/agent_startup.py", line 31, in load_pth_files
site.addsitedir(site_dir)
File "<frozen site>", line 236, in addsitedir
File "<frozen site>", line 188, in addpackage
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte
```
So we are now just skipping such dirs. There is a risk that we might miss some useful pth files, but I …

fix(agent): skip site dirs that have bad .pth files

---

src/isolate/connections/grpc/agent.py

We can already get SerializationError on the client side when serialising the object, so it would be expected to also get that error from the remote when deserialising instead of getting a generic abort and `print_exc` to the stdout logs. This will allow us to handle serialisation errors nicely on the client side..

feat(isolate): return SerializationError instead of aborting

---

src/isolate/connections/common.py

We are using and installing tblib already, so we should also use it to improve basic exception handling in general, even if our user code didn't manage to patch it yet (e.g. we got a serialization error before we even could run it).

feat: install tblib pickling support

---

src/isolate/connections/common.py

tblib's install() will search for BaseException subclasses, so we have to call it after the SerializationError is defined.

fix: install tblib after SerializationError
